# =============================================================
# EJBCA — Configuration base de données PostgreSQL
# Les valeurs réelles sont injectées via variables d'env
# =============================================================
datasource.jndi-name=EjbcaDS
datasource.jndi-name-audit=EjbcaAuditDS

# Pool de connexions
datasource.pool.size.initial=5
datasource.pool.size.max=50
datasource.pool.size.min=5
datasource.pool.idle-timeout-minutes=5
