# =============================================================
# EJBCA — Configuration interface web
# =============================================================

httpserver.hostname=pki-ca
httpserver.external.fqdn=pki-ca

# Authentification admin par certificat client
web.reqcertindb=true
web.allowedadmin.certificate=true

# Langues supportées
supported.languages=EN;FR
default.language=FR

# Limites de taille des fichiers (upload CSR, P12)
web.requestfile.maxbytes=65536
